version: "3"
services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - pg-network
    extra_hosts:
      - host.docker.internal:host-gateway
  pgadmin4:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin4
    restart: "always"
    environment:
      PGADMIN_DEFAULT_EMAIL: "mingguobin@live.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pg-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgadmin4-data:

networks:
  pg-network:
    external: false
