version: "3"
services:
  gitea:
    image: docker.io/gitea/gitea:1.22.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=host.docker.internal:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - APP_NAME=大明二代的gitea
      - SSH_PORT=1022
      - SSH_LISTEN_PORT=1022
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "13000:3000"
      - "1022:1022"
    extra_hosts:
      - host.docker.internal:host-gateway
  runner:
    image: gitea/act_runner:0.2.11
    container_name: gitea_runner
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: ZgiuCRK1UEZq6Br7EZk5mzjOkVEmwzwlNWcbQ5jC
      # GITEA_RUNNER_NAME: "damingerdai gitea runner"
      GITEA_RUNNER_NAME: 大明二代
      # gitea中的run-on使用的这个labels
      GITEA_RUNNER_LABELS: "ubuntu-latest"
    volumes:
      - ./runner-config.yaml:/config.yaml
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea

  runner2:
    build:
      context: ./
      dockerfile: runner.Dockerfile
    container_name: custom_gitea_runner
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: pH62IR2hvXPXj0k3cuQYwOURJz8PHH5zggkFM7KU
      GITEA_RUNNER_NAME: "damingerdai custom gitea runner"
      GITEA_RUNNER_LABELS: "default_runner"
    volumes:
      - ./runner-config2.yaml:/config.yaml
      - ./runner-data2:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea

networks:
  gitea:
    external: false
