services:
  gitea:
    image: docker.io/gitea/gitea:1.26
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=host.docker.internal:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - APP_NAME=大明二代的gitea
      - SSH_PORT=1022
      - SSH_LISTEN_PORT=1022
      #- GITEA__actions__ENABLED=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "13000:3000"
      - "1022:1022"
    extra_hosts:
      - host.docker.internal:host-gateway
  runner:
    image: gitea/act_runner:0.6.0
    container_name: gitea_runner
    depends_on:
      - gitea
    environment:
      CONFIG_FILE: /config.yaml
      # GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_INSTANCE_URL: http://192.168.31.220:13000
      GITEA_RUNNER_REGISTRATION_TOKEN: Efz7im2XZCgbawmSo5ynO4YZEXZ8mW5cQx4dqFnd
      GITEA_RUNNER_NAME: "damingerdai gitea runner"
    volumes:
      - ./config.yaml:/config.yaml
      - ./runner-data:/data
      - ./runner-data/cache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock # 允许 Runner 访问 Docker Socket
    networks:
      - gitea
networks:
  gitea:
    driver: bridge
