global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "health master online"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["50.3.199.4:8000"]
