services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql-9.4
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
      MYSQL_USER: daming
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - mysql-network
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  mysql-network:
    external: false
