services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z # 指定版本[5](@ref)
    container_name: minio_server
    restart: unless-stopped
    ports:
      - "19000:9000" # API 端口（S3 协议）
      - "19001:9001" # 控制台端口（Web 管理界面）[5](@ref)
    environment:
      MINIO_ROOT_USER: admin # 管理员账号（≥3字符）
      MINIO_ROOT_PASSWORD: 12345678 # 密码需≥8字符
    volumes:
      - ./minio_data:/data # 数据持久化目录[1,5](@ref)
    command: server /data --console-address ":9001" # 固定控制台端口[5](@ref)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
