services:
  mongo:
    image: mongo:8.0.12-noble
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sw23895881
    volumes:
      - ./data:/data/db
    command: mongod --auth --bind_ip_all
